#!/bin/bash
set -e
shopt -s extglob

MODE=$1

if [[ $MODE != "release" && $MODE != "debug" ]]; then
    echo "❌ Invalid mode. Must be 'release' or 'debug'"
    exit 1
fi

if [[ ! -e "Package.swift" || ! -e "Calendr.xcodeproj" ]]; then
    echo "❌ This script must be run from the project root directory"
    exit 1
fi

XCODE_CONFIG="Release"
[[ "$MODE" == "debug" ]] && XCODE_CONFIG="Debug"

has_xcode() {
    xcrun actool --version &>/dev/null
}

get_build_setting() {
    echo "$BUILD_SETTINGS" | awk -v key="$1" -F ' = ' '$1 == "    " key { print $2; exit }'
}

if has_xcode; then
    echo -e "\n🔧 Xcode detected — generating assemble.env from Calendr.xcodeproj\n"

    BUILD_SETTINGS=$(xcodebuild -showBuildSettings \
        -project Calendr.xcodeproj \
        -target Calendr \
        -configuration "$XCODE_CONFIG" 2>/dev/null)

    {
        echo "# Generated by assemble.sh"
        echo "PRODUCT_BUNDLE_IDENTIFIER=$(get_build_setting PRODUCT_BUNDLE_IDENTIFIER)"
        echo "MARKETING_VERSION=$(get_build_setting MARKETING_VERSION)"
        echo "CURRENT_PROJECT_VERSION=$(get_build_setting CURRENT_PROJECT_VERSION)"
        echo "MACOSX_DEPLOYMENT_TARGET=$(get_build_setting MACOSX_DEPLOYMENT_TARGET)"
    } > assemble.env
fi

if [[ ! -f assemble.env ]]; then
    echo "❌ Missing assemble.env"
    exit 1
fi

set -a
source assemble.env
set +a

# Generate app icon
if has_xcode; then
    echo -e "\n🔧 Xcode detected — generating AppIcon.icns\n"

    mkdir -p .build/resources

    xcrun actool "Calendr/Assets/Images.xcassets" \
        --compile .build/resources \
        --platform macosx \
        --minimum-deployment-target "$MACOSX_DEPLOYMENT_TARGET" \
        --app-icon AppIcon \
        --output-partial-info-plist ".build/asset-info.plist" \
        --output-format human-readable-text \
        > /dev/null

    cp .build/resources/AppIcon.icns resources/
fi

# Build the Binary
swift build -c $MODE

# Configuration
CONFIG_DIR="Calendr/Config"
BUILD_DIR="$(swift build -c $MODE --show-bin-path)"
APP_BUNDLE=".build/Calendr.app"
CONTENTS="$APP_BUNDLE/Contents"
PLIST="$CONTENTS/Info.plist"

# Clean up and Create Folders
rm -rf "$APP_BUNDLE"
mkdir -p "$CONTENTS/MacOS"
mkdir -p "$CONTENTS/Resources"
mkdir -p "$CONTENTS/Frameworks"

# Copy the Binary
cp "$BUILD_DIR/Calendr" "$CONTENTS/MacOS/"

# Copy the existing Info.plist
cp "$CONFIG_DIR/Info.plist" "$CONTENTS/Info.plist"

# Copy Frameworks (like Sentry)
cp -R "$BUILD_DIR"/*.framework "$CONTENTS/Frameworks/"

# Copy resource bundles to Contents/Resources/
for bundle in "$BUILD_DIR"/*.bundle; do
    name=$(basename "$bundle")
    rm -rf "$CONTENTS/Resources/$name"
    cp -R "$bundle" "$CONTENTS/Resources/"
done

echo -e "\n💉 Injecting values: ID=$PRODUCT_BUNDLE_IDENTIFIER, Version=$MARKETING_VERSION, Build=$CURRENT_PROJECT_VERSION\n"

plutil -replace CFBundleIdentifier -string "$PRODUCT_BUNDLE_IDENTIFIER" "$PLIST"
plutil -replace CFBundleShortVersionString -string "$MARKETING_VERSION" "$PLIST"
plutil -replace CFBundleVersion -string "$CURRENT_PROJECT_VERSION" "$PLIST"
plutil -replace LSMinimumSystemVersion -string "$MACOSX_DEPLOYMENT_TARGET" "$PLIST"
plutil -replace CFBundleExecutable -string "Calendr" "$PLIST"
plutil -replace CFBundleName -string "Calendr" "$PLIST"
plutil -replace CFBundlePackageType -string "APPL" "$PLIST"
plutil -replace CFBundleIconFile -string "AppIcon" "$PLIST"
plutil -replace CFBundleIconName -string "AppIcon" "$PLIST"

if [[ -f resources/AppIcon.icns ]]; then
    cp resources/AppIcon.icns "$CONTENTS/Resources/"
else
    echo -e "⚠️  resources/AppIcon.icns not found — app will have no icon.\n"
fi

prepare_entitlements() {
    local dest="$1"
    cp "assemble.entitlements" "$dest"

    if [[ "$MODE" == "debug" ]]; then
        plutil -insert 'com\.apple\.security\.get-task-allow' -bool true "$dest"
    fi
}

sign_framework() {
    local framework="$1"
    local name="${framework%.framework}"
    name="${name##*/}"
    local binary="$framework/Versions/Current/$name"

    if [[ -f "$binary" ]]; then
        codesign --force --sign "$SIGN_IDENTITY" --options runtime "$binary"
    fi
    codesign --force --sign "$SIGN_IDENTITY" --options runtime "$framework"
}

# Ad-hoc signing keeps local assemble builds launchable without Gatekeeper
# developer verification (Apple Development certs trigger that check).
SIGN_IDENTITY="-"
ENTITLEMENTS=$(mktemp)
prepare_entitlements "$ENTITLEMENTS"

echo -e "\n🔏 Signing with ad-hoc identity (sandbox entitlements)\n"

while IFS= read -r -d '' framework; do
    sign_framework "$framework"
done < <(find "$CONTENTS/Frameworks" -name "*.framework" -print0 2>/dev/null)

# Sign the app bundle with entitlements and hardened runtime
codesign --force --sign "$SIGN_IDENTITY" --entitlements "$ENTITLEMENTS" --options runtime "$APP_BUNDLE"

echo "✅ $APP_BUNDLE assembled successfully!"
