name: Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR Caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh cache delete --ref "refs/pull/${PR_NUMBER}/merge" --all
