name: Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR Caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh cache delete \
          --repo ${REPOSITORY} \
          --ref "refs/pull/${PR_NUMBER}/merge" \
          --all --succeed-on-no-caches
