name: Cleanup

on:
  push:
    branches: [master]

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR Caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
        run: |
          PR_NUMBERS=$( \
            gh pr list \
            --repo ${REPOSITORY} \
            --state closed \
            --limit 100 \
            --json number,closedAt \
            | \
            jq -r '. | sort_by(.closedAt) | .[-5:] | .[].number' \
          )

          for PR_NUMBER in $PR_NUMBERS; do
            gh cache delete \
              --repo ${REPOSITORY} \
              --ref "refs/pull/${PR_NUMBER}/merge" \
              --all --succeed-on-no-caches
          done
