name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    if: &not-draft github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: Unit Tests
    runs-on: &macos macos-26
    permissions:
      actions: write
      checks: write
    env:
      scheme: Calendr

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache SPM
        uses: actions/cache@v6
        with:
          path: |
            .build/checkouts
            .build/repositories
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Test
        run: |
          set -o pipefail && swift test --skip-update --xunit-output=./report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          check_name: 'Test Report'
          report_paths: './report.xml'

  assemble-env:
    if: *not-draft
    name: Assemble env
    runs-on: *macos

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check assemble.env
        run: |
          ./assemble.sh env
          git diff --exit-code -- assemble.env
